---

- hosts: all
  user: joel
  become: true
  tasks:


  - name: update repository index
    dnf:
      update_cache: true

  - name: install htop package
    dnf:
      name: htop
      state: latest
