---

- hosts: all
  user: joel
  become: true
  tasks:


  - name: update repository index
    dnf:
      update_cache: true
    when: ansible_distribution in ["Rocky Linux", "Centos"]

  - name: install htop package
    dnf:
      name: htop
      state: latest
    when: ansible_distribution == "Rocky Linux"
